### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by gatosyperros** [ianka/xfs_undelete#11]
Hey it's not an issue per se, but I was wondering if it would detect if it had recovered the same file before?

I carelessly deleted a decent amount of files about 600GB so when I went into recovering the files I was faced with an issue, "how would I store all of it if it manages to fined everyting?"
I had to go find some of the external hard drives drives I had laying around, thankfully I had about 700GB left on one of them.

My issue was that I wanted to start restoring the files as quick as possible so I launched the scrip and noticed that it was quickly filling up my drive, so I switched to another bigger drive and after a couple of hours realized that it might not be enough.

I tried moving the recovered files off to a another computer while it was recovering in fear I of stopping it again, but it only ended up clipping the poor drive.

So basically I have just two question and one request, Would it over write the files if I started recovering in the same folder, or would it detect the duplicate?
and what would happen if the recovery drive ended up out of space?

request:
could it be possible to start recovering from inode X 
I still don't know how it all works, but basically if I stop the recovery for some reason, could it be possible to implement a function where I could "resume" the recovery?

Also THANK YOU!! I got 500GB back!
Now all I have to do is rename the files, thankfully most of them were RAR files that kept the original name inside the archive, and some movies with subtitles, or text files that had the original name.

reading around the net you only hear horror stories about rm -rf :)

I'm glad I decided to look further because the first recovery tools ended up giving me corrupted file back (probably because they were made for ext3,4

**Comment by ianka** [comment]
> My issue was that I wanted to start restoring the files as quick as possible 

First rule of data recovery: don't panic.

Imagine me, when I wrote this script a year ago because I lost some video files.

Don't panic.

> Would it over write the files if I started recovering in the same folder, or would it detect the duplicate?

Each inode number in the source filesystem is unique, and so are the names of the recovered files. If you restarted the script, it would simply overwrite the result file with exactly the same contents as it had before.

In your case, I rather stopped the script (Crtl+Z) instead of interrupting it (Crtl+C), moved the already recovered files to a third disk, then continued the script with `fg`.


> what would happen if the recovery drive ended up out of space?

At the moment, all unexpected errors in `dd` are caught and discarded, so it would try to write into the output directory but couldn't, and you won't notice it.

I should change this behaviour, I think.


> could it be possible to start recovering from inode X

The tricky part about specifying an inode range is the script has no control in which order the inodes are visited, as it traverses the inode tree recursively. It dependes on the filesystem whether the tree traversal leads to a monotonic series of inode numbers.

But yes, if the script fails due to missing space in the output filesystem, it could leave a message how to restart from exactly that point.



> thankfully most of them were RAR files that kept the original name inside the archive

Hmm, I could add a facility to rename such files automatically. Archives, music, videos, such.

**Comment by ianka** [comment]
Feature added in v9.0. Please see the manpage for the -s option.

**Comment by gatosyperros** [comment]
Nice , I think this could be useful since generally the disk shouldn't change when recovering so the ionode tree should change either.
It could be useful in some scenarios,hopefully I won't ever need it :)
