### ISSUE TITLE
`Please specify a block device or an XFS filesystem image.`

### ISSUE THREAD

**Issue by devvace** [ianka/xfs_undelete#12]
hi,
i entered `single user mode` using the command: `# telinit 1`
and
i used the following command but got the error. 
```
[root@localhost ~]# xfs_undelete /dev/mapper/centos-root
Please specify a block device or an XFS filesystem image.
```
plz give me some advice.
thanks!

**Comment by ianka** [comment]
You found a bug! Xfs_undelete tries to find out the real device node behind symlinks and returns this message if it can't resolve the symlink. But … what if that file isn't a symlink?

To resolve this quickly, create a symlink pointing to /dev/mapper/centos-root, and feed that symlink into xfs_undelete.

Could you please also show me the result of ```# ls -l /dev/mapper/centos-root``` and ```# readlink -e /dev/mapper/centos-root```?

**Comment by devvace** [comment]
thx for your reply!
I tried with symlink and found a different result.
```
[root@localhost ~]# readlink -e /dev/mapper/centos-root
/dev/dm-0

[root@localhost ~]# xfs_undelete /dev/dm-0
/dev/dm-0 (/dev/dm-0) is currently mounted read-write. Trying to remount read-only.
mount: / is busy
```

and.. I trying to remount read-only.
```
[root@localhost ~]# mount -o remount -o rw /dev/dm-0
[root@localhost ~]# xfs_undelete /dev/dm-0
Please specify a block device or an XFS filesystem image.
```
What should I do..?
thanks!

**Comment by ianka** [comment]
Ok. The bug is a misleading error message. It should be ```Remount failed. mount: /: mount point is busy.```
Xfs_undelete only matches on mount's error message ```mount: * mount point is busy.```, not ```mount: * is busy.``` Could you please tell me the output of ```$ mount --version``` on your machine so I can fix this for your OS? — Which one, by the way?

---
All that aside, ```mount: / is busy``` tells the real problem. Before xfs_undelete is able to work on a filesystem, it must be read-only. That because XFS maintains a journal that is only cleared and written to disk on umount/remount read-only.

But you cannot remount a filesystem read-only if you have r/w opened files on it. That poses a bit of a hen and egg problem if it is your root filesystem your want to recover from. So, what can you do?

- [ ] Remove the harddisk with your root filesystem from your computer and connect is as an additional harddisk to another computer. Start xfs_undelete on that other computer and tell it to recover from your harddisk.

**or**

- [ ] Boot your computer from an USB stick with a Linux distribution having tclsh, tcllib, and xfs_undelete. You want to prepare that stick on another computer so you don't overwrite files on your harddisk. Start xfs_undelete from within the USB stick Linux and tell it to recover from your harddisk.

These are the **_sane_** options. If you are in a hurry and don't care about the journal, you could also comment out the ```exit 32``` in line 465 of the script. Maybe I add this as an option.

**Don't forget to specify ```-o your_external_recovery_directory``` on a different hard disk or USB stick!**

**Comment by ianka** [comment]
I fixed the misleading mount error message bug with version 9.1 and added a --no-remount-readonly option as a feature which may help you with version 10.0.

**Comment by devvace** [comment]
First of all, Thanks for your kind reply 👍 
My `mount` version is
```
[root@localhost ~]# mount --version
mount from util-linux 2.23.2 (libmount 2.23.0: selinux, debug, assert)
```
I used `CentOS 7.4`.

I'll give it a try as you say.
I hope it works :)
