### ISSUE TITLE
No nodes found ..

### ISSUE THREAD

**Issue by eMPee584** [ianka/xfs_undelete#17]
Hi,
just went through the other reports of "nothing found"; I deleted a single JPEG file by accident.. first I ran `time xfs_undelete -t -48hour /dev/disk/by-label/attik` overnight, thinking this will surely take quite the while.. Actually it only takes 90 seconds It successfully remounted the partition read-only..
This is a
`Linux base 5.8.0-1-amd64 #1 SMP Debian 5.8.7-1 (2020-09-05) x86_64 GNU/Linux` machine, with `tcl 8.6.9+1+b1` and `tcllib 1.20+dfsg-1`. 
```
# file --version
file-5.38
magic file from /etc/magic:/usr/share/misc/magic
# file --brief --mime-type /etc/magic
text/plain
```
The mount is 
```
/dev/sdd3 /mnt/attik xfs ro,noatime,attr2,inode64,logbufs=8,logbsize=32k,noquota 0 0

  Filesystem      Size  Used Avail Use% Mounted on
  /dev/sdd3       2.6T  2.6T  3.1G 100% /mnt/attik
```

I also tried without time limit, with `-i ""`, directly specifying the device (`/dev/sdd3`)..
Wanted to turn the verbosity higher but no idea how to do that with tclsh.
The file is probably very irrelevant, just wanted to use this as a test case. Glad to dig deeper though.. best regards ; )

**Comment by eMPee584** [comment]
Ok out of interest I ran it on another xfs partition.. it found some files.. But really really few! Can't imagine these are all files deleted recently..
Quite strange, is it the `xfs-reclaim` kernel worker threads that kill the inodes, or what? :thinking: 

```
/dev/sdc2 (/dev/sdc2) is currently mounted read-write. Trying to remount read-only.
Remount successful.
Starting recovery.
Done.                             %)(100%))

real    6m30.791s
user    1m55.076s
sys     0m22.714s
```
Another crowded volume, NOT A SINGLE deleted FILE found?! :open_mouth:

**Comment by ianka** [comment]
> Actually it only takes 90 seconds

That's normal. Xfs_undelete walks the Inode B-Tree rather than scanning the whole disk for data fragments. With standard XFS filesystem settings, it should complete in roughly 2 minutes.

> Wanted to turn the verbosity higher

The script is as verbose as it gets in the default setting already. You should see a progress line updated with each inode scanned, and one line per deleted and matching inode found. If it doesn't find anything, chances are the filesystem wasn't properly umounted so the file isn't deleted in the inode B-tree yet. Or your -t specifcation simply doesn't match.

> Can't imagine these are all files deleted recently.. Another crowded volume, NOT A SINGLE deleted FILE found?

Another reason might be the inode simply got reused already. XFS does that pretty quickly.

**Comment by ianka** [comment]
You might want to try to change [line 164 of the script](https://github.com/ianka/xfs_undelete/blob/master/xfs_undelete#L164)

    if {[string range $data $boffset $boffset+7] ne "IN\0\0\3\2\0\0"} continue

into

    if {[string range $data $boffset $boffset+3] ne "IN\0\0" || [string range $data $boffset+6 $boffset+7] ne "\0\0"} continue

This because the script might be too picky about the magic string of a deleted inode. On all XFS filesystems I encountered yet the inode type was 3 and the fork type was 2 after deletion, but it may be different on yours.

**Comment by eMPee584** [comment]
Okey, I tried the proposed relaxation of inode filter but it made no difference. `xfs_undelete` found the same five text files on one volume and **no** files on any of the other partitions.. very strange. So there seems to be a very low likelihood of recovery on XFS? :thinking: 
I've yet to try deleting a file and directly after running the script..

**Comment by ianka** [comment]
Well, I lost 60 video files by accidentally moving them to a nonexistant directory *Video* instead of *Videos* through a misparametered ```find```. It renamed each of them *Video* and moved each of them over the previous, deleting the previous one in the process. That was my motivation to write this script. And yes, it got them all back. So it's possible to recover files from XFS with *xfs_undelete*. If you umount quickly before another process creates new files.

**Comment by ianka** [comment]
You might want to try

    if {[string range $data $boffset $boffset+3] ne "IN\0\0"} continue

then, but that may "recover" false positives. You could also run ```xfs_info``` on those filesystems and post the result. Maybe that reports something unusual.

**Comment by ianka** [comment]
You haven't replied for a week. I'm closing this issue. Feel free to reopen it if you have new information.
