### ISSUE TITLE
Restored file is 4.0 EB big

### ISSUE THREAD

**Issue by rems0** [ianka/xfs_undelete#36]
Hi, 

first thank you for the nice recovery tool!

I am trying to recover some files removed some hours ago, and I get several 4.0 EB big files that are difficult to deal with afterwards.
The block device where I start the recovery is a 59 TB hardware raid.
I have tried the -z option, both with txt and text/* but I still get the 4.0 EB file.
Am I doing something wrong or how can I get a smaller file?

Many thanks,
Richard

**Comment by ianka** [comment]
Such extraordinary huge files are likely bogus. The only valid reason to have such a file is that it is sparse. That means, it consists of zeroes mostly. Pretty much only databases and tools as bittorrent which combine several source files in place create valid files of that sort.

**Comment by rems0** [comment]
Hi,
I managed to extract the relevant data from that file. It was on the first 16606 lines. Using sed or vim was a no go, they filled up the memory and got killed. I managed to extract the data using head -n NNN and try&error to guess the number of lines.

You may want to close this issue as solved, but isn't there an option to avoid this huge files? How can a file be bigger as the underlying FS? Why does -z not work here?
Anyhow, many thanks for xfs_undelete, nice work!

Thanks,
Richard

**Comment by ianka** [comment]
There's already a lot of sanity check in xfs_undelete. The one that usually triggers is that those huge bogus sparse file often have no data at position 0 and following. But yours had. I don't know.

> How can a file be bigger as the underlying FS? 

It's a sparse file. It does not occupy that space on the original filesystem. You have to think of it as e.g. one block at position 0 and another block at position 18446744073709551616. It only takes 8192 bytes on disk then.

> Why does -z not work here?

Because -z does only delete zeroes at the end of a file, not zeroes inbetween. Oh, and it has the same problems with huge files as vim and sed.
