### ISSUE TITLE
invalid command name "lmap"

### ISSUE THREAD

**Issue by LeandroDATAFull** [ianka/xfs_undelete#39]
./xfs_undelete

invalid command name "lmap"
    while executing
"lmap t $times {
                if {[catch {clock scan $t} t]} {
                        puts stderr "Unable to parse time range. Please put it as a range of time specs Tcl's \[clock sc..."
    (procedure "parseTimerange" line 13)
    invoked from within
"parseTimerange [dict get $::parameters t]"
    invoked from within
"set ctimes [parseTimerange [dict get $::parameters t]]"
    (file "./xfs_undelete" line 453)

Centos 7

Package 1:tcl-8.5.13-8.el7.x86_64

**Comment by ianka** [comment]
That's because the Tcl version that comes with your OS is 8.5. The last release of Tcl-8.5 has been more than six years ago, and Tcl-8.6 is stable since about nine years ago.

**Comment by Huangmp1996** [comment]
I met the same problem. After I install tcl-8.6.1 manually and xfs_undelete 11.0, it was solved. Thank you to the authors @ianka  !

**Comment by ianka** [comment]
You are welcome. I mark this issue as solved then.

**Comment by xloem** [comment]
i found this project from a link on stackexchange. its possible it hasn’t gotten more upvotes because it is hard to upgrade systems when recovering files from them. much easier to make use of old libraries and binaries in a readonly manner.

**Comment by ianka** [comment]
I see, but this year Tcl-8.6 has it's tenth birthday. So it's for sure old software at this point.

**Comment by xloem** [comment]
Yes, one tends to find old software on dying systems. What’s notable is that Tcl seems pretty reasonable to build from source, it has few dependencies.

**Comment by ianka** [comment]
Umm, but xfs_undelete is not about recovering files from dying hard drives and such.

It's for files you have recently deleted. Like, a minute ago or so. And you want them back.

**Comment by xloem** [comment]
thanks, i seem dissociated around that. leaves me confused. maybe i just wanted to be right.

personally i have a very old system, and mostly just still have it because of my persecutory dissociation, my other part deletes my files so i try hard to not delete things, which leaves me with little space and other issues detering upgrading.

thanks for your work implementing this. it didn't work for me, found no deleted files in the past day from my mounted filesystem, not sure why. i ended up recovering my files via other channels.

**Comment by ianka** [comment]
Xfs_undelete is unfortunately not really bulletproof in recovering files, even when they have been deleted recently. XFS has just too many options and also too many ways to store files.

That's why I made xfs_undelete only ever **read** from the source filesystem. So you can't lose anything by trying it out.
